version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: skillbridge_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: skillbridge
      POSTGRES_USER: skillbridge_user
      POSTGRES_PASSWORD: skillbridge_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data: