spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/skillbridge
spring.datasource.username=skillbridge_user
spring.datasource.password=skillbridge_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect